### ISSUE TITLE
FIX java.lang.ClassNotFoundException: tv.twelvetone.gradle.plugin.navigation.components.MyProjectComponent

### ISSUE THREAD

**Issue by allanlaal** [Flamenco/GradleNavigationPluginDistribution#1]
IntelliJ IDEA 2021.3.3 (Ultimate Edition)
Build #IU-213.7172.25, built on March 15, 2022
	  
  Plugin 'tv.twelvetone.gradle.plugin.navigation' failed to initialize and will be disabled. Please restart IntelliJ IDEA.
	  
	  java.lang.ClassNotFoundException: tv.twelvetone.gradle.plugin.navigation.components.MyProjectComponent
	               PluginClassLoader(plugin=PluginDescriptor(name=Gradle/Maven Navigation, id=tv.twelvetone.gradle.plugin.navigation, descriptorPath=plugin.xml, path=~/.local/share/JetBrains/IntelliJIdea2021.3/GradleNavigationPlugin.jar, version=1.0.48, package=null, isBundled=false), packagePrefix=null, instanceId=248, state=active)
	      at com.intellij.serviceContainer.ComponentManagerImplKt.doLoadClass(ComponentManagerImpl.kt:1443)
	      at com.intellij.serviceContainer.ComponentManagerImplKt.access$doLoadClass(ComponentManagerImpl.kt:1)
	      at com.intellij.serviceContainer.ComponentManagerImpl.loadClass(ComponentManagerImpl.kt:821)
	      at com.intellij.serviceContainer.BaseComponentAdapter.getImplementationClass(BaseComponentAdapter.kt:38)
	      at com.intellij.serviceContainer.BaseComponentAdapter.getInstanceUncached(BaseComponentAdapter.kt:107)
	      at com.intellij.serviceContainer.BaseComponentAdapter.getInstance(BaseComponentAdapter.kt:67)
	      at com.intellij.serviceContainer.BaseComponentAdapter.getInstance$default(BaseComponentAdapter.kt:60)
	      at com.intellij.serviceContainer.ComponentManagerImpl.createComponents(ComponentManagerImpl.kt:401)
	      at com.intellij.openapi.project.impl.ProjectExImpl.init(ProjectExImpl.kt:180)
	      at com.intellij.openapi.project.impl.ProjectManagerImpl.initProject(ProjectManagerImpl.java:179)
	      at com.intellij.openapi.project.impl.ProjectManagerExImpl.prepareProject(ProjectManagerExImpl.kt:342)
	      at com.intellij.openapi.project.impl.ProjectManagerExImpl.access$prepareProject(ProjectManagerExImpl.kt:58)
	      at com.intellij.openapi.project.impl.ProjectManagerExImpl$doOpenAsync$1.invoke(ProjectManagerExImpl.kt:125)
	      at com.intellij.openapi.project.impl.ProjectManagerExImpl$doOpenAsync$1.invoke(ProjectManagerExImpl.kt:58)
	      at com.intellij.openapi.project.impl.ProjectUiFrameAllocator$run$progressRunner$1.apply(ProjectFrameAllocator.kt:94)
	      at com.intellij.openapi.project.impl.ProjectUiFrameAllocator$run$progressRunner$1.apply(ProjectFrameAllocator.kt:71)
	      at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:244)
	      at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:188)
	      at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:624)
	      at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:698)
	      at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:646)
	      at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:623)
	      at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:66)
	      at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:175)
	      at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:244)
	      at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	      at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1692)
	      at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	      at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	      at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	      at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	      at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)

**Comment by Flamenco** [comment]
@allanlaal Did this work on previous version, and failed after you upgraded?

**Comment by allanlaal** [comment]
I havent used it before

**Comment by mmnm8878** [comment]
I have the same issue. I've never used it before and now I can't start IDEA. I also can't figure out how to remove the plugin manually without starting IDEA. Do you know how to solve this?

**Comment by Flamenco** [comment]
@mmnm8878 

I will try to have a look at this today and upload a fix.  

In the meantime, have a look here for manual removal:
https://intellij-support.jetbrains.com/hc/en-us/community/posts/360000524244-Disable-Uninstall-plugin-without-launching-Idea

**Comment by Flamenco** [comment]
This was fixed and submitted to IntelliJ.

Version 1.1.0

It should be approved by Jetbrains in a day or two.

**Comment by mmnm8878** [comment]
@Flamenco 
Thank you.
